export default {
  ['zh-CN']: {
    '_settings': {
      rootWidth: '350px',
      numberInputMinWidth: '42px',
      controlWidth: '215px',
    },
    'ui.subtitle': '基于WebGL2的液态玻璃效果模拟工具',
    'editor.basicSettings': '基础设置',
    'editor.language': '语言',
    'editor.refThickness': '折射厚度',
    'editor.refFactor': '折射系数',
    'editor.refDispersion': '色散增益',
    'editor.refFresnelRange': '菲涅尔反射范围',
    'editor.refFresnelHardness': '菲涅尔反射硬度',
    'editor.refFresnelFactor': '菲涅尔反射强度',
    'editor.glareRange': '高光范围',
    'editor.glareHardness': '高光硬度',
    'editor.glareConvergence': '高光聚拢度',
    'editor.glareOppositeFactor': '高光对侧强度',
    'editor.glareFactor': '高光强度',
    'editor.glareAngle': '高光角度',
    'editor.blurRadius': '模糊半径',
    'editor.blurEdge': '模糊边缘',
    'editor.tint': '色调',
    'editor.shadowExpand': '阴影扩散',
    'editor.shadowFactor': '阴影强度',
    'editor.shadowPosition': '阴影位置',
    'editor.bgType': '背景',
    'editor.shapeSettings': '形状设置',
    'editor.shapeWidth': '宽',
    'editor.shapeHeight': '高',
    'editor.shapeRadius': '圆角 (%)',
    'editor.shapeRoundness': '超椭圆系数',
    'editor.mergeRate': '形状融合度',
    'editor.showShape1': '显示第二个图形',
    'editor.selfIllumination': '自发光',
    'editor.emissiveColor': '发光颜色',
    'editor.emissiveIntensity': '发光强度',
    'editor.emissivePulse': '呼吸动画',
    'editor.hdrSettings': 'HDR 光照',
    'editor.hdrEnabled': '启用 HDR',
    'editor.hdrExposure': '曝光',
    'editor.hdrToneMappingType': '色调映射',
    'editor.hdrBloom': '泛光',
    'editor.textSettings': '文字设置',
    'editor.textEnabled': '启用文字',
    'editor.textContent': '文字内容',
    'editor.textSize': '文字大小',
    'editor.textFont': '字体',
    'editor.textSuperSample': '超采样',
    'editor.animationSettings': '动画设置',
    'editor.springSizeFactor': '动画形变',
    'editor.debugSettings': '调试',
    'editor.export': '导出预设',
    'editor.import': '导入预设',
    'editor.importSuccessMessage': '预设导入成功！',
    'editor.importFailedMessage': (message: string) => `导入失败：${message}`,
    'editor.builtInPresets': '玻璃预设',
    'editor.preset.crystalClear': '水晶',
    'editor.preset.frostedGlass': '磨砂玻璃',
    'editor.preset.tintedWindow': '彩色玻璃',
    'editor.preset.diamond': '钻石',
    'editor.preset.waterDrop': '水滴',
    'editor.preset.soapBubble': '肥皂泡',
    'editor.preset.ice': '冰',
    'editor.preset.obsidian': '黑曜石',
    'editor.uiContentSettings': 'UI内容',
    'editor.uiContentEnabled': '启用UI内容',
    'editor.uiContentType': '内容类型',
    'editor.uiContentText': '自定义文字',
    'editor.uiContentOpacity': '内容透明度',
    'editor.uiContentType.clock': '时钟',
    'editor.uiContentType.weather': '天气',
    'editor.uiContentType.music': '音乐播放器',
    'editor.uiContentType.custom-text': '自定义文字',
    'editor.showcase': '动画演示',
    'editor.showcase.rainbowPrism': '彩虹棱镜',
    'editor.showcase.shapeMorph': '形状变换',
    'editor.showcase.glowPulse': '发光脉冲',
    'editor.showcase.diamondSparkle': '钻石闪烁',
    'editor.showcase.frostMelt': '霜融化',
    'editor.editorMode': '编辑器模式',
    'editor.editorModeSettings': '编辑器模式',
    'editor.addShape': '添加形状',
    'editor.deleteShape': '删除形状',
    'editor.shapeList': '形状列表',
    'editor.shape': '形状',
  },
  ['en-US']: {
    '_settings': {
      rootWidth: '400px',
      numberInputMinWidth: '42px',
      controlWidth: '215px',
    },
    'ui.subtitle': 'Liquid Glass Effect Simulation Tool based on WebGL2',
    'editor.basicSettings': 'Basic Settings',
    'editor.language': 'Language',
    'editor.refThickness': 'Thickness',
    'editor.refFactor': 'Refraction Factor',
    'editor.refDispersion': 'Dispersion Gain',
    'editor.refFresnelRange': 'Fresnel Size',
    'editor.refFresnelHardness': 'Fresnel Hardness',
    'editor.refFresnelFactor': 'Fresnel Intensity',
    'editor.glareRange': 'Glare Size',
    'editor.glareHardness': 'Glare Hardness',
    'editor.glareConvergence': 'Glare Convergence',
    'editor.glareOppositeFactor': 'Glare Opposite Side',
    'editor.glareFactor': 'Glare Intensity',
    'editor.glareAngle': 'Glare Angle',
    'editor.blurRadius': 'Blur Radius',
    'editor.blurEdge': 'Blur Edge',
    'editor.tint': 'Tint',
    'editor.shadowExpand': 'Shadow Expand',
    'editor.shadowFactor': 'Shadow Intensity',
    'editor.shadowPosition': 'Shadow Position',
    'editor.bgType': 'Background',
    'editor.shapeSettings': 'Shape Settings',
    'editor.shapeWidth': 'Width',
    'editor.shapeHeight': 'Height',
    'editor.shapeRadius': 'Radius (%)',
    'editor.shapeRoundness': 'SuperEllipse Factor',
    'editor.mergeRate': 'Merge Rate',
    'editor.showShape1': 'Show 2nd Shape',
    'editor.selfIllumination': 'Self-Illumination',
    'editor.emissiveColor': 'Emissive Color',
    'editor.emissiveIntensity': 'Emissive Intensity',
    'editor.emissivePulse': 'Pulse Animation',
    'editor.hdrSettings': 'HDR Illumination',
    'editor.hdrEnabled': 'Enable HDR',
    'editor.hdrExposure': 'Exposure',
    'editor.hdrToneMappingType': 'Tone Mapping',
    'editor.hdrBloom': 'Bloom',
    'editor.textSettings': 'Text Settings',
    'editor.textEnabled': 'Enable Text',
    'editor.textContent': 'Text Content',
    'editor.textSize': 'Text Size',
    'editor.textFont': 'Font',
    'editor.textSuperSample': 'Super Sample',
    'editor.animationSettings': 'Animation Settings',
    'editor.springSizeFactor': 'Animation Morph',
    'editor.debugSettings': 'Debug',
    'editor.export': 'Export Preset',
    'editor.import': 'Import Preset',
    'editor.importSuccessMessage': 'Preset imported successfully!',
    'editor.importFailedMessage': (message: string) => `Import failed: ${message}`,
    'editor.builtInPresets': 'Glass Presets',
    'editor.preset.crystalClear': 'Crystal Clear',
    'editor.preset.frostedGlass': 'Frosted Glass',
    'editor.preset.tintedWindow': 'Tinted Window',
    'editor.preset.diamond': 'Diamond',
    'editor.preset.waterDrop': 'Water Drop',
    'editor.preset.soapBubble': 'Soap Bubble',
    'editor.preset.ice': 'Ice',
    'editor.preset.obsidian': 'Obsidian',
    'editor.uiContentSettings': 'UI Content',
    'editor.uiContentEnabled': 'Enable UI Content',
    'editor.uiContentType': 'Content Type',
    'editor.uiContentText': 'Custom Text',
    'editor.uiContentOpacity': 'Content Opacity',
    'editor.uiContentType.clock': 'Clock',
    'editor.uiContentType.weather': 'Weather',
    'editor.uiContentType.music': 'Music Player',
    'editor.uiContentType.custom-text': 'Custom Text',
    'editor.showcase': 'Showcase',
    'editor.showcase.rainbowPrism': 'Rainbow Prism',
    'editor.showcase.shapeMorph': 'Shape Morph',
    'editor.showcase.glowPulse': 'Glow Pulse',
    'editor.showcase.diamondSparkle': 'Diamond Sparkle',
    'editor.showcase.frostMelt': 'Frost Melt',
    'editor.editorMode': 'Editor Mode',
    'editor.editorModeSettings': 'Editor Mode',
    'editor.addShape': 'Add Shape',
    'editor.deleteShape': 'Delete Shape',
    'editor.shapeList': 'Shape List',
    'editor.shape': 'Shape',
  },
  ['uz-UZ']: {
    '_settings': {
      "rootWidth": "400px",
      "numberInputMinWidth": "42px",
      "controlWidth": "215px"
    },
    "ui.subtitle": "WebGL2 asosidagi Liquid Glass effekt simulyatori",
    "editor.basicSettings": "Asosiy sozlamalar",
    "editor.language": "Til",
    "editor.refThickness": "Qalinlik",
    "editor.refFactor": "Sinish koeffitsiyenti",
    "editor.refDispersion": "Dispersiya darajasi",
    "editor.refFresnelRange": "Fresnel o‘lchami",
    "editor.refFresnelHardness": "Fresnel qattiqligi",
    "editor.refFresnelFactor": "Fresnel intensivligi",
    "editor.glareRange": "Yaltiroq maydoni",
    "editor.glareHardness": "Yaltiroq qattiqligi",
    "editor.glareConvergence": "Yaltiroq to‘planishi",
    "editor.glareOppositeFactor": "Qarama-qarshi tomon yorqinligi",
    "editor.glareFactor": "Yaltiroq intensivligi",
    "editor.glareAngle": "Yaltiroq burchagi",
    "editor.blurRadius": "Xiralashish radiusi",
    "editor.blurEdge": "Xiralashish qirralar",
    "editor.tint": "Rang ohangi",
    "editor.shadowExpand": "Soya kengligi",
    "editor.shadowFactor": "Soya kuchi",
    "editor.shadowPosition": "Soya joylashuvi",
    "editor.bgType": "Fon turi",
    "editor.shapeSettings": "Shakl sozlamalari",
    "editor.shapeWidth": "Kenglik",
    "editor.shapeHeight": "Balandlik",
    "editor.shapeRadius": "Radius (%)",
    "editor.shapeRoundness": "Burchak yumaloqligi",
    "editor.mergeRate": "Qo‘shilish tezligi",
    "editor.showShape1": "2-shaklni ko‘rsatish",
    "editor.selfIllumination": "O'z-o'zini yoritish",
    "editor.emissiveColor": "Yorug'lik rangi",
    "editor.emissiveIntensity": "Yorug'lik kuchi",
    "editor.emissivePulse": "Puls animatsiyasi",
    "editor.hdrSettings": "HDR yoritish",
    "editor.hdrEnabled": "HDR yoqish",
    "editor.hdrExposure": "Ekspozitsiya",
    "editor.hdrToneMappingType": "Ton xaritalash",
    "editor.hdrBloom": "Bloom",
    "editor.textSettings": "Matn sozlamalari",
    "editor.textEnabled": "Matnni yoqish",
    "editor.textContent": "Matn mazmuni",
    "editor.textSize": "Matn o'lchami",
    "editor.textFont": "Shrift",
    "editor.textSuperSample": "Super namuna",
    "editor.animationSettings": "Animatsiya sozlamalari",
    "editor.springSizeFactor": "Animatsiya deformatsiyasi",
    "editor.debugSettings": "Debug",
    "editor.export": "Presetni eksport qilish",
    "editor.import": "Presetni import qilish",
    "editor.importSuccessMessage": "Preset muvaffaqiyatli import qilindi!",
    "editor.importFailedMessage": (message: string) => `Import failed: ${message}`,
    'editor.builtInPresets': 'Shisha presetlari',
    'editor.preset.crystalClear': 'Kristall',
    'editor.preset.frostedGlass': 'Muzlatilgan shisha',
    'editor.preset.tintedWindow': 'Rangli oyna',
    'editor.preset.diamond': 'Olmos',
    'editor.preset.waterDrop': "Suv tomchisi",
    'editor.preset.soapBubble': "Sovun pufagi",
    'editor.preset.ice': 'Muz',
    'editor.preset.obsidian': 'Obsidian',
    'editor.uiContentSettings': 'UI Kontent',
    'editor.uiContentEnabled': 'UI Kontentni yoqish',
    'editor.uiContentType': 'Kontent turi',
    'editor.uiContentText': 'Maxsus matn',
    'editor.uiContentOpacity': 'Kontent shaffofligi',
    'editor.uiContentType.clock': 'Soat',
    'editor.uiContentType.weather': "Ob-havo",
    'editor.uiContentType.music': 'Musiqa pleyeri',
    'editor.uiContentType.custom-text': 'Maxsus matn',
    'editor.showcase': 'Namoyish',
    'editor.showcase.rainbowPrism': 'Kamalak prizma',
    'editor.showcase.shapeMorph': 'Shakl o\'zgarishi',
    'editor.showcase.glowPulse': 'Yorqinlik pulsi',
    'editor.showcase.diamondSparkle': 'Olmos yarqirashi',
    'editor.showcase.frostMelt': 'Qirov erishi',
    'editor.editorMode': 'Tahrirlash rejimi',
    'editor.editorModeSettings': 'Tahrirlash rejimi',
    'editor.addShape': "Shakl qo'shish",
    'editor.deleteShape': "Shaklni o'chirish",
    'editor.shapeList': "Shakllar ro'yxati",
    'editor.shape': 'Shakl',
  }
}
